Domain Name Server Option
tobychui/zoraxy pull request #406
Opened 2024-12-01 03:31 UTC by Sickjuicy

Adds a function to select DNS servers

2024-12-01 07:56 UTC, tobychui requested changes
Thanks so much for the PR!

I have read it and you really done a great job adding the new DNS server option for ACME. I have raised a few questions and concern in the PR, maybe you can check and see if you can optimize it further before I merge it into main. 

If you are too busy to update it, I can also change your merge target to a new branch and I will continue your work from there.

@yeungalan as you are the primary author of the ACME module, I guess you shd take a look at the changes as well. Apologies to bother you during the thanksgiving holiday, you can PM me directly when you are free.

2024-12-01 07:56 UTC, tobychui commented on src/mod/acme/acme.go
> +		DNSServers:  strings.Split(dnsServers, ","),
I am a bit worry that a space will exists between the `dnsServers` and comma, specially in cases where the user manually write the config file in vim (or other text editors)
e.g. `dns1.example.com, dns2.example.com`
I guess the better way to do so is iterate and clean the dnsServers entry one by one using something like

```
servers := strings.Split(dnsServers, ",")
    for i := range servers {
        servers[i] = strings.TrimSpace(servers[i])
    }
```

2024-12-01 07:56 UTC, tobychui commented on src/mod/acme/acme.go
> +		if dnsServers == "" && len(certInfo.DNSServers) > 0 {
As you have added a new field `DNSservers`, when a user using old cert info config file, the `certInfo.DNSServers` will be `nil`. You will also need to check if `certInfo.DNSServers == nil` before this line.

2024-12-01 15:07 UTC, Sickjuicy commented
I updated it and tested it 

normal behavior 
"dnsServers":["ns1.example.com","ns2.example.com"]}



Something put in custom 

dnsServers":[" ns1.example.com  , ns2.example.com"]}

will be updated to after starting the renew process to
"dnsServers":["ns1.example.com","ns2.example.com"]} 

the same if the variable does not yet exist 
result: 

"dnsServers":[""]} 

it will than just uses the standard resolver from google and cloudflare

2024-12-02 22:45 UTC, tobychui approved these changes
LGTM, @yeungalan please have a look and let me know if it is ready to merge, thanks!

2024-12-03 03:30 UTC, yeungalan approved these changes

2024-12-06 11:28 UTC, tobychui approved these changes

2024-12-06 11:29 UTC, merged